<?php
/** Included by campus-integration-test.php after its isolated WP/MySQL bootstrap. */
if (!function_exists('expect') || !defined('WP_INSTALLING')) exit(2);
require_once dirname(__DIR__).'/includes/class-olama-emis-staff.php';
require_once dirname(__DIR__).'/includes/class-olama-emis-import.php';
require_once dirname(__DIR__).'/includes/class-olama-emis-staff-export.php';
require_once dirname(__DIR__).'/includes/class-olama-emis-staff-admin.php';
expect(Olama_EMIS_Staff::install(),'Staff tables install');
expect(Olama_EMIS_Staff::install(),'Staff schema repeats safely');
$staff_service=new Olama_EMIS_Staff();
$wpdb->insert('test_olama_core_student_years',array('school_id'=>'2','school_name'=>'مدرسة ثانية','study_year'=>'2025-2026'));
$staff_input=array('school_id'=>'1','study_year'=>'2025-2026','identity_number'=>'٠٠١٢٣٤٥٦٧٨','identity_type'=>'personal','first_name'=>'سارة','father_name'=>'أحمد','grandfather_name'=>'محمد','family_name'=>'الاختبار','birth_date'=>'1988-02-29','job_title'=>'معلم','total_experience'=>'12','education_experience'=>'10','gross_salary'=>'800.50','reported_periods'=>'30','phone'=>'0790000000','languages'=>'العربية، الإنجليزية','employment_basis'=>'دوام كامل');
$staff_id=success($staff_service->save_person($staff_input),'Create staff and assignment');
$staff=$staff_service->find($staff_id); $assignment=$staff_service->assignment($staff_id,'1','2025-2026');
expect($staff['identity_number']==='0012345678' && $staff['identity_type']==='personal','Arabic digits and leading zeros survive');
expect(is_wp_error($staff_service->save_person($staff_input)),'Duplicate identity cannot create another staff');
expect(is_wp_error($staff_service->save_person(array_merge($staff_input,array('staff_id'=>$staff_id,'staff_revision'=>0,'assignment_revision'=>1)))),'Stale staff update rejected');
$edit=array_merge($staff_input,array('staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'assignment_revision'=>$assignment['revision'],'total_experience'=>'5'));
expect(is_wp_error($staff_service->save_person($edit)),'Experience inequality rejected');
expect($staff_service->find($staff_id)['revision']===$staff['revision'],'Failed edit rolls back');
$edit=array('school_id'=>'2','study_year'=>'2025-2026','staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'assignment_revision'=>0,'job_title'=>'معلم');
success($staff_service->save_person($edit),'Same employee assigned to second school');
$staff=$staff_service->find($staff_id);
expect((int)$wpdb->get_var('SELECT COUNT(*) FROM '.Olama_EMIS_Staff::table())===1,'Shared identity remains one record');
$qinput=array('staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'degree'=>'بكالوريوس','specialization'=>'رياضيات','graduation_date'=>'2010-06-01','graduation_country'=>'الأردن','institution'=>'جامعة الاختبار','evaluation'=>'جيد جداً','is_highest'=>1);
$qid=success($staff_service->save_qualification($qinput),'Save degree');
$staff=$staff_service->find($staff_id);
$qid2=success($staff_service->save_qualification(array_merge($qinput,array('staff_revision'=>$staff['revision'],'degree'=>'ماجستير','graduation_date'=>'2015-06-01','bachelor_specialization'=>'رياضيات'))),'Save postgraduate degree');
expect(count($staff_service->qualifications($staff_id))===2 && (int)$staff_service->find($staff_id)['highest_qualification_id']===$qid2,'Multiple degrees and selected highest');
$staff=$staff_service->find($staff_id);
expect(is_wp_error($staff_service->save_qualification(array_merge($qinput,array('staff_revision'=>$staff['revision'],'qualification_id'=>9999)))),'Foreign/missing qualification rejected');
$work_ctx=array('staff_id'=>$staff_id,'school_id'=>'1','study_year'=>'2025-2026','assignment_revision'=>$assignment['revision'],'reported_periods'=>'30');
$work_rows=array(array('subject'=>'رياضيات','grade'=>'العاشر','section'=>'أ','weekly_periods'=>'20'),array('subject'=>'رياضيات','grade'=>'العاشر','section'=>'ب','weekly_periods'=>'10'));
success($staff_service->save_workloads($work_ctx,$work_rows),'Save load above internal warning limit');
$summary=$staff_service->load_summary($staff_id,'2025-2026');expect($summary['total']===30 && $summary['warnings'],'Workload sums and threshold warning');
expect(is_wp_error($staff_service->save_workloads($work_ctx,array())),'Stale workload cannot erase rows');
expect(count($staff_service->workloads($assignment['id']))===2,'Stale edit preserves distributions');
$work_ctx['assignment_revision']=2;
expect(is_wp_error($staff_service->save_workloads($work_ctx,array($work_rows[0],$work_rows[0]))),'Duplicate subject/grade/section rejected');
$bad=$work_rows; $bad[0]['weekly_periods']='-1';expect(is_wp_error($staff_service->save_workloads($work_ctx,$bad)),'Negative load rejected');
$staff=$staff_service->find($staff_id);
success($staff_service->save_person(array('staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'assignment_revision'=>0,'school_id'=>'1','study_year'=>'2026-2027','job_title'=>'معلم')),'New academic-year assignment');
expect(count($staff_service->workloads($assignment['id']))===2 && $staff_service->load_summary($staff_id,'2026-2027')['total']===0,'Year separation preserves old workload');
$staff=$staff_service->find($staff_id);
success($staff_service->save_person(array('staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'assignment_revision'=>2,'school_id'=>'1','study_year'=>'2025-2026','identity_number'=>'0009876543')),'Correct national/personal identifier');
expect(count($staff_service->qualifications($staff_id))===2 && count($staff_service->workloads($assignment['id']))===2,'Identifier correction preserves all links');
$preview=success($staff_service->preview_import(array(array('identity_number'=>'0009876543','phone'=>'0791111111')),array('school_id'=>'1','study_year'=>'2025-2026'),'update'),'Import update preview');
expect($preview[0]['error']==='' && (int)$preview[0]['input']['staff_id']===$staff_id,'Import matches existing assignment');
success($staff_service->save_person($preview[0]['input']),'Apply import row');
expect($staff_service->find($staff_id)['profile']['father_name']==='أحمد','Omitted import columns preserved');
expect(is_wp_error($staff_service->save_person($preview[0]['input'])),'Preview revisions prevent stale confirmation');
$p=success($staff_service->preview_import(array($staff_input,$staff_input),array('school_id'=>'1','study_year'=>'2025-2026'),'add'),'Duplicate file preview');expect($p[1]['error']!=='','File duplicate caught before save');
$p=success($staff_service->preview_import(array(array('identity_number'=>'0009876543')),array('school_id'=>'1','study_year'=>'2025-2026'),'add'),'Add-mode existing preview');expect($p[0]['error']!=='','Add mode refuses existing staff');
$p=success($staff_service->preview_import(array(array('identity_number'=>'0000000011')),array('school_id'=>'1','study_year'=>'2025-2026'),'update'),'Update missing preview');expect($p[0]['error']!=='','Update mode refuses missing assignments');
expect(is_wp_error($staff_service->save_person(array_merge($staff_input,array('school_id'=>'999')))),'Unknown school blocked');
for($i=0;$i<26;$i++) success($staff_service->save_person(array_merge($staff_input,array('identity_number'=>'900000'.str_pad((string)$i,4,'0',STR_PAD_LEFT),'first_name'=>'موظف'.$i))),'Staff pagination fixture');
$list=$staff_service->list_staff(array('school_id'=>'1','study_year'=>'2025-2026'),'',2,25);expect($list['total']===27 && count($list['rows'])===2,'Server pagination gives complete second page');
expect(count($staff_service->lookup('سارة'))===1,'Autocomplete finds Arabic name');
expect($staff_service->list_staff(array('school_id'=>'1','study_year'=>'2025-2026'),'0009876543',1,25)['total']===1,'Identity search scoped to school');
$path=success(Olama_EMIS_Staff_Export::xlsx(array('identity_number','first_name','family_name','birth_date'),array(array('0009876543','سارة','الاختبار','1988-02-29'))),'XLSX export');
$parsed=success(Olama_EMIS_Import::rows($path,'staff.xlsx',Olama_EMIS_Staff::import_fields(),'identity_number'),'XLSX reimport');
expect($parsed[0]['identity_number']==='0009876543' && $parsed[0]['first_name']==='سارة','Excel roundtrip preserves IDs and Arabic');unlink($path);
expect(Olama_EMIS_Staff_Export::csv_value('=HYPERLINK("https://example.invalid")')[0]==="'",'CSV formula injection prevented');
$write_caps=static function($caps){$caps['olama_users_ministry_view']=true;$caps['olama_users_ministry_configure']=true;return $caps;};add_filter('user_has_cap',$write_caps,20);
$staff_admin=new Olama_EMIS_Staff_Admin();
foreach(array('staff','qualifications')as$module){
    $_GET=array('page'=>'olama-emis-'.$module,'school_id'=>'1','study_year'=>'2025-2026','staff_id'=>$staff_id);
    ob_start();$staff_admin->page();$html=ob_get_clean();
    expect(strpos($html,'0009876543')!==false,'Staff admin renders identity');
    expect(strpos($html,$module==='staff'?'معاينة الملف':'olama-emis__workload-template')!==false,'Staff module controls render');
    $preview_dir=getenv('EMIS_TEST_PREVIEW_DIR');
    if($preview_dir && is_dir($preview_dir)){
        $css=file_get_contents(ABSPATH.'wp-includes/css/buttons.min.css').file_get_contents(dirname(__DIR__).'/assets/admin.css');$js=file_get_contents(dirname(__DIR__).'/assets/staff.js');
        file_put_contents($preview_dir.'/'.$module.'.html','<!doctype html><html lang="ar" dir="rtl"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>EMIS '.$module.'</title><style>body{background:#f0f0f1;font-family:Arial,sans-serif;margin:20px}input,select{padding:8px;border:1px solid #aebdc7}</style><style>'.$css.'</style><body class="wp-core-ui">'.$html.'<script>'.$js.'</script></body></html>');
    }
}
remove_filter('user_has_cap',$write_caps,20);
ob_start();$staff_admin->page();$readonly=ob_get_clean();expect(strpos($readonly,'fieldset disabled')!==false && strpos($readonly,'olama-emis__add-workload')===false,'Viewer cannot edit qualifications/workload');
$staff=$staff_service->find($staff_id);$assignment=$staff_service->assignment($staff_id,'1','2025-2026');
success($staff_service->save_person(array('staff_id'=>$staff_id,'staff_revision'=>$staff['revision'],'assignment_revision'=>$assignment['revision'],'school_id'=>'1','study_year'=>'2025-2026','archived'=>1)),'Archive staff assignment');
$work_ctx['assignment_revision']=(int)$assignment['revision']+1;expect(is_wp_error($staff_service->save_workloads($work_ctx,array())),'Archived assignment rejects load edits');
expect($staff_service->load_summary($staff_id,'2025-2026')['total']===0,'Archived loads excluded from current total');
echo "Staff integration passed: identities, assignments, qualifications, workload warnings, revisions, imports, Excel roundtrip, pagination and permissions.\n";
